#!/usr/bin/ruby

require 'open-uri'
require 'pp'

$stream = open(ARGV[0])
$in = false
$url = ""
$title = ""

while (line = $stream.gets)
    if not $in and line =~ /class="dev-description"/
        $in = true
    elsif $in
        nxt = false
        scn = line.scan(/(next|<a.*? href="(.*?)".*? title="(.*?)".*?<\/a>)/i)
        pp scn
        scn.each do |mtc|
            pp mtc
            if mtc[0] =~ /next/i
                nxt = true
            else
                $url = mtc[1]
                m = /^(.*?) by/.match(mtc[2])
                $title = m[1]
            end
        end
        break
    end
end

if not $url.empty?
    puts $url
    puts $title
    puts "No description" # To get the description, we need to download another page
end

