#!/usr/bin/ruby

require 'open-uri'

$stream = open(ARGV[0])
$in = false
$url = ""
$title = ""

while (line = $stream.gets)
    if not $in and line =~ /class="dev-description"/
        $in = true
    elsif $in
        nxt = false
        lines = line.split(/next/i)
        lines.each do |ln|
            mt = /<a.*?href="(.*?)".*?title="(.*?)"/.match(ln)
            if not mt.nil?
                $url = mt[1]
                $title = mt[2]
            end
        end

        break
    end
end

if not $url.empty?
    puts $url
    puts $title.split(/[[:blank:]]*by/)[0]
    puts "No description" # To get the description, we need to download another page
end

